Update exporters.md - Adding missing library to example instrumentation.js
The example instrumentation.js had a missing library PeriodicExportingMetricReader

when running the example as-is with node --require ./instrumentation.js app.js

The user would get an error:
ReferenceError: PeriodicExportingMetricReader is not defined