Fix TypeError in Python getting-started.md
The code under the Metrics section of Python getting-started.md [1]
fails with the following traceback when the "player" query parameter is
specified and not empty:

```
Traceback (most recent call last):
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/flask/app.py\", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File \"/Users/jl-martins/Projects/otel-python-getting-started/app.py\", line 22, in roll_dice
    return str(roll())
               ~~~~^^
  File \"/Users/jl-martins/Projects/otel-python-getting-started/app.py\", line 33, in roll
    logger.info(\"{} is rolling the dice: {}\", player, result)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 1522, in info
    self._log(INFO, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 1667, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 1686, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 1744, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 1027, in handle
    self.emit(record)
    ~~~~~~~~~^^^^^^^^
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py\", line 569, in emit
    logger.emit(self._translate(record))
                ~~~~~~~~~~~~~~~^^^^^^^^
  File \"/Users/jl-martins/Projects/otel-python-getting-started/.venv/lib/python3.13/site-packages/opentelemetry/sdk/_logs/_internal/__init__.py\", line 539, in _translate
    body = record.getMessage()
  File \"/Users/jl-martins/.local/share/mise/installs/python/3.13.5/lib/python3.13/logging/__init__.py\", line 400, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
TypeError: not all arguments converted during string formatting
```

This happens because "{}" is not a valid format specifier as of
Python 3.13 logging [2].

The closest format supported by the standard logging library is that of
`str.format` [3], however, the other log statements in this guide
are using % formatting, so this PR fixes the aforementioned error by using
% formatting, for the sake of consistency.

[1] https://github.com/open-telemetry/opentelemetry.io/edit/main/content/en/docs/languages/python/getting-started.md
[2] https://docs.python.org/3.13/library/logging.html
[3] https://docs.python.org/3.13/library/stdtypes.html#str.format